galaxy_info:
  author: Stas Arts
  role_name: elasticsearch
  namespace: avt0m8
  description: Install elasticsearch from remote server
  company: Netology

  license: BSD-3-Clause

  min_ansible_version: 2.8

  galaxy_tags: [elasticsearch]

dependencies: []
